import './styles/globals.scss';
import 'material-symbols';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import BootstrapClient from './components/BootstrapClient';
import AppNavbar from './components/AppNavbar';
import AppFooter from './components/AppFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/vercel.svg' sizes='any' />
      </head>
      <body className={inter.className}>
        <AppNavbar />
        {children}
        <AppFooter />
        <BootstrapClient />
      </body>
    </html>
  );
}
